"""Per-app oauth2-proxy compose builder + Dokploy provisioner.

Carved out of dashboard-sync.py (see BACKLOG_TECHNICAL.md "dashboard-sync.py
decomposition"). Builds the `oauth2-proxy-clients` compose for gated CLIENT
apps and find-or-creates / redeploys it in the infrastructure project.
Stdlib-only; installed beside dashboard-sync on the host.
"""
from __future__ import annotations

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import dokploy_api  # noqa: E402


def build_clients_compose(specs, env):
    """Render the docker-compose for the per-app oauth2-proxy instances of
    gated CLIENT apps. One `oauth2-proxy-<slug>` service per spec, flags
    mirroring roles/oauth2_proxy/templates/oauth2-proxy.compose.yml.j2 --
    same shared Keycloak client + cookie, differing only in --allowed-group
    (from the app's resolved groups) and --upstream (the app's backend).
    Secrets are embedded literally, matching the Ansible-managed infra
    compose (Dokploy encrypts the stored composeFile at rest)."""
    port = env["OAUTH2_PROXY_INTERNAL_PORT"]
    zone = env["CLOUDFLARE_ZONE"]
    out = [
        "# Auto-generated by dashboard-sync -- do not edit by hand.",
        "# Per-app oauth2-proxy instances for gated CLIENT apps. Infra app",
        "# proxies live in the Ansible-managed `oauth2-proxy` compose.",
        "services:",
    ]
    for s in specs:
        svc = f"oauth2-proxy-{s['slug']}"
        out += [
            f"  {svc}:",
            f'    image: "{env["OAUTH2_PROXY_IMAGE"]}"',
            "    environment:",
            f'      OAUTH2_PROXY_CLIENT_SECRET: "{env["OAUTH2_PROXY_CLIENT_SECRET"]}"',
            f'      OAUTH2_PROXY_COOKIE_SECRET: "{env["OAUTH2_PROXY_COOKIE_SECRET"]}"',
            "    command:",
            f'      - "--http-address=0.0.0.0:{port}"',
            '      - "--reverse-proxy=true"',
            '      - "--provider=keycloak-oidc"',
            f'      - "--oidc-issuer-url={env["OAUTH2_PROXY_OIDC_ISSUER"]}"',
            f'      - "--client-id={env["OAUTH2_PROXY_CLIENT_ID"]}"',
            f'      - "--cookie-name={env["OAUTH2_PROXY_COOKIE_NAME"]}"',
            f'      - "--cookie-domain=.{zone}"',
            '      - "--cookie-secure=true"',
            '      - "--cookie-samesite=lax"',
            f'      - "--whitelist-domain=.{zone}"',
            '      - "--email-domain=*"',
            '      - "--scope=openid email profile groups"',
            '      - "--oidc-groups-claim=groups"',
            f'      - "--upstream=http://{s["upstream_alias"]}:{s["upstream_port"]}"',
        ]
        # Group names without leading slash (realm groups claim has
        # full.path=false). DENY apps resolve to ['admin'] only.
        for g in s["allowed_groups"]:
            out.append(f'      - "--allowed-group={g}"')
        out += [
            '      - "--set-xauthrequest=true"',
            '      - "--pass-user-headers=true"',
            '      - "--pass-access-token=false"',
            '      - "--silence-ping-logging=true"',
            '      - "--skip-provider-button=true"',
            "    networks:",
            "      dokploy-network:",
            "        aliases:",
            f'          - "{svc}"',
            "    restart: unless-stopped",
        ]
    out += ["networks:", "  dokploy-network:", "    external: true", ""]
    return "\n".join(out)


def provision_clients_compose(api_base, api_key, projects, infra_project, specs, env):
    """Find-or-create the `oauth2-proxy-clients` Dokploy compose in the
    infrastructure project and (re)deploy it when its body changes.
    Declarative `compose up` recreates only changed services, so adding
    one client app does not disturb the others' live SSO sessions.

    Non-fatal: any Dokploy API error here is logged and the sync
    continues (the route files are still written; the proxy just is not
    refreshed until the next run)."""
    name = env["OAUTH2_PROXY_CLIENTS_COMPOSE"]
    if not specs:
        print(
            f"dashboard-sync: no gated client apps -- leaving {name} as-is "
            f"(no teardown)."
        )
        return
    proj = next((p for p in projects if p.get("name") == infra_project), None)
    if not proj or not proj.get("environments"):
        print(
            f"dashboard-sync/warn: infra project {infra_project!r} or its "
            f"environment not found; cannot provision {name}.",
            file=sys.stderr,
        )
        return
    environment = proj["environments"][0]
    env_id = environment.get("environmentId")
    existing = next(
        (c for c in (environment.get("compose") or []) if c.get("name") == name),
        None,
    )
    body = build_clients_compose(specs, env)
    try:
        if existing is None:
            created = dokploy_api.dokploy_post(
                api_base, "/compose.create", api_key,
                {
                    "name": name, "environmentId": env_id,
                    "composeType": "docker-compose", "appName": name,
                    "composeFile": "", "serverId": None,
                },
            )
            compose_id = created.get("composeId")
        else:
            compose_id = existing.get("composeId")
        current = dokploy_api.dokploy_get(api_base, f"/compose.one?composeId={compose_id}", api_key)
        if isinstance(current, dict) and current.get("composeFile") == body:
            print(f"dashboard-sync: {name} compose unchanged ({len(specs)} instance(s)).")
            return
        dokploy_api.dokploy_post(
            api_base, "/compose.update", api_key,
            {"composeId": compose_id, "composeFile": body, "sourceType": "raw"},
        )
        dokploy_api.dokploy_post(api_base, "/compose.deploy", api_key, {"composeId": compose_id})
        print(f"dashboard-sync: (re)deployed {name} ({len(specs)} instance(s)).")
    except RuntimeError as e:
        print(f"dashboard-sync/warn: {name} provisioning failed: {e}", file=sys.stderr)
