"""Per-app oauth2-proxy compose builder + Portainer provisioner.

Carved out of dashboard-sync.py (see BACKLOG_TECHNICAL.md "dashboard-sync.py
decomposition"). Builds the `oauth2-proxy-clients` compose for gated CLIENT
apps and find-or-creates / redeploys it in the infrastructure project.
Stdlib-only; installed beside dashboard-sync on the host.
"""
from __future__ import annotations

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import portainer_api  # noqa: E402


def build_clients_compose(specs, env):
    """Render the docker-compose for the per-app oauth2-proxy instances of
    gated CLIENT apps. One `oauth2-proxy-<slug>` service per spec, flags
    mirroring roles/oauth2_proxy/templates/oauth2-proxy.compose.yml.j2 --
    same shared Keycloak client + cookie, differing only in --allowed-group
    (from the app's resolved groups) and --upstream (the app's backend).
    Secrets are embedded literally, matching the Ansible-managed infra
    compose."""
    port = env["OAUTH2_PROXY_INTERNAL_PORT"]
    zone = env["CLOUDFLARE_ZONE"]
    out = [
        "# Auto-generated by dashboard-sync -- do not edit by hand.",
        "# Per-app oauth2-proxy instances for gated CLIENT apps. Infra app",
        "# proxies live in the Ansible-managed `oauth2-proxy` compose.",
        "services:",
    ]
    for s in specs:
        svc = f"oauth2-proxy-{s['slug']}"
        out += [
            f"  {svc}:",
            f'    image: "{env["OAUTH2_PROXY_IMAGE"]}"',
            "    environment:",
            f'      OAUTH2_PROXY_CLIENT_SECRET: "{env["OAUTH2_PROXY_CLIENT_SECRET"]}"',
            f'      OAUTH2_PROXY_COOKIE_SECRET: "{env["OAUTH2_PROXY_COOKIE_SECRET"]}"',
            "    command:",
            f'      - "--http-address=0.0.0.0:{port}"',
            '      - "--reverse-proxy=true"',
            '      - "--provider=keycloak-oidc"',
            f'      - "--oidc-issuer-url={env["OAUTH2_PROXY_OIDC_ISSUER"]}"',
            # Skip boot-time OIDC discovery (a public CF-tunnel GET) and pin
            # explicit endpoints: login PUBLIC (browser), token + JWKS intra-
            # cluster. Removes Cloudflare from the auth boot path so a tunnel
            # re-register during a restore cannot crashloop this container.
            '      - "--skip-oidc-discovery=true"',
            f'      - "--login-url={env["OAUTH2_PROXY_LOGIN_URL"]}"',
            f'      - "--redeem-url={env["OAUTH2_PROXY_REDEEM_URL"]}"',
            f'      - "--oidc-jwks-url={env["OAUTH2_PROXY_JWKS_URL"]}"',
            f'      - "--client-id={env["OAUTH2_PROXY_CLIENT_ID"]}"',
            f'      - "--cookie-name={env["OAUTH2_PROXY_COOKIE_NAME"]}"',
            f'      - "--cookie-domain=.{zone}"',
            '      - "--cookie-secure=true"',
            '      - "--cookie-samesite=lax"',
            f'      - "--whitelist-domain=.{zone}"',
            '      - "--email-domain=*"',
            '      - "--scope=openid email profile groups"',
            '      - "--oidc-groups-claim=groups"',
            f'      - "--upstream=http://{s["upstream_alias"]}:{s["upstream_port"]}"',
        ]
        # Group names without leading slash (realm groups claim has
        # full.path=false). DENY apps resolve to ['admin'] only.
        for g in s["allowed_groups"]:
            out.append(f'      - "--allowed-group={g}"')
        out += [
            '      - "--set-xauthrequest=true"',
            '      - "--pass-user-headers=true"',
            '      - "--pass-access-token=false"',
            '      - "--silence-ping-logging=true"',
            '      - "--skip-provider-button=true"',
            "    networks:",
            "      catena-network:",
            "        aliases:",
            f'          - "{svc}"',
            "    restart: unless-stopped",
        ]
    out += ["networks:", "  catena-network:", "    external: true", ""]
    return "\n".join(out)


def provision_clients_compose(api_base, api_key, specs, env):
    """Find-or-create the `oauth2-proxy-clients` Portainer stack and
    (re)deploy it when its body changes. Declarative `compose up` recreates
    only changed services, so adding one client app does not disturb the
    others' live SSO sessions.

    Non-fatal: any Portainer API error here is logged and the sync continues
    (the route files are still written; the proxy just is not refreshed until
    the next run)."""
    name = env["OAUTH2_PROXY_CLIENTS_COMPOSE"]
    if not specs:
        print(
            f"dashboard-sync: no gated client apps -- leaving {name} as-is "
            f"(no teardown)."
        )
        return
    body = build_clients_compose(specs, env)
    headers = {"X-API-Key": api_key, "accept": "application/json"}
    try:
        endpoint_id = portainer_api.portainer_endpoint_id(api_base, api_key)
        existing = next(
            (s for s in portainer_api.list_stacks(api_base, api_key)
             if s.get("Name") == name),
            None,
        )
        if existing is None:
            portainer_api.http_json(
                f"{api_base}/stacks/create/standalone/string?endpointId={endpoint_id}",
                headers,
                {"Name": name, "StackFileContent": body, "Env": []},
                method="POST",
            )
            print(f"dashboard-sync: created {name} ({len(specs)} instance(s)).")
            return
        stack_id = existing.get("Id")
        if portainer_api.stack_file(api_base, api_key, stack_id) == body:
            print(f"dashboard-sync: {name} stack unchanged ({len(specs)} instance(s)).")
            return
        # PUT is update == synchronous redeploy. Image is pinned, so no
        # PullImage on the routine env refresh. Env preserved verbatim.
        portainer_api.http_json(
            f"{api_base}/stacks/{stack_id}?endpointId={endpoint_id}",
            headers,
            {"StackFileContent": body, "Env": existing.get("Env") or [],
             "PullImage": False, "Prune": False},
            method="PUT",
        )
        print(f"dashboard-sync: (re)deployed {name} ({len(specs)} instance(s)).")
    except (RuntimeError, SystemExit) as e:
        print(f"dashboard-sync/warn: {name} provisioning failed: {e}", file=sys.stderr)
