"""Traefik gate-route rendering + access resolution for dashboard-sync.

Pure functions: render the per-app Traefik dynamic-config file and resolve
an app's access posture. `resolve_access` is now a thin wrapper over the
canonical helpers/labels_schema.resolve_auth_mode -- the former drift-prone
inlined copy of the resolution logic is gone (see BACKLOG_TECHNICAL.md
"dashboard-sync.py decomposition"). Stdlib-only; installed beside
dashboard-sync on the host (labels_schema.py ships alongside, so the bare
`from labels_schema import ...` fallback resolves there).
"""
from __future__ import annotations

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
try:
    # In-repo (pytest / operator uv-run with pythonpath=automation).
    from helpers.labels_schema import last_warnings, resolve_auth_mode, slugify
except ModuleNotFoundError:
    # On host: labels_schema.py is installed flat beside dashboard-sync.
    from labels_schema import last_warnings, resolve_auth_mode, slugify

AUTO_ROUTE_SUFFIX = "-auto-gate.yml"
# Legacy filename suffix from before the Keycloak/oauth2-proxy migration.
# The cleanup loop in sync_gate_routes scans both suffixes and removes any
# file not in the desired set, so old "-auto-authentik.yml" files are
# deleted within one sync after this script is updated.
_LEGACY_AUTO_ROUTE_SUFFIX = "-auto-authentik.yml"


def _route_yaml_public(name, host, alias, port, force_https_mw):
    """Render the Traefik dynamic-config file for a `vps.auth.mode=public`
    app. Single router, force-https only, priority 100."""
    slug = slugify(name)
    return (
        f"# Auto-generated by dashboard-sync -- do not edit by hand.\n"
        f"# Source compose: {name}; backend: http://{alias}:{port}.\n"
        f"# PUBLIC -- no forward-auth (vps.auth.mode=public).\n"
        f"http:\n"
        f"  routers:\n"
        f"    {slug}-auto-gate:\n"
        f'      rule: "Host(`{host}`)"\n'
        f"      priority: 100\n"
        f"      entryPoints:\n"
        f"        - web\n"
        f"      middlewares:\n"
        f"        - {force_https_mw}@file\n"
        f"      service: {slug}-auto-gate-svc\n"
        f"  services:\n"
        f"    {slug}-auto-gate-svc:\n"
        f"      loadBalancer:\n"
        f"        servers:\n"
        f'          - url: "http://{alias}:{port}"\n'
    )


def _proxy_alias(name):
    """dokploy-network alias of the per-app oauth2-proxy instance for this
    app. Matches the service name dashboard-sync renders in the
    oauth2-proxy-clients compose."""
    return f"oauth2-proxy-{slugify(name)}"


def _route_yaml_perapp(name, host, force_https_mw, proxy_port):
    """Render the Traefik dynamic-config file for a gated app in
    reverse-proxy mode: a single priority-100 router that sends the WHOLE
    host (including /oauth2/*) to this app's own oauth2-proxy instance,
    which authenticates then proxies to the backend via its own
    `--upstream`. Mirrors roles/oauth2_proxy/templates/app-oauth2-proxy.yml.j2
    (no callback subrouter -- the per-app proxy owns /oauth2/* on its
    Host). Priority 100 beats Dokploy's auto-generated router."""
    slug = slugify(name)
    proxy = _proxy_alias(name)
    return (
        f"# Auto-generated by dashboard-sync -- do not edit by hand.\n"
        f"# Source compose: {name}; gated via its own {proxy} instance.\n"
        f"http:\n"
        f"  routers:\n"
        f"    {slug}-auto-gate:\n"
        f'      rule: "Host(`{host}`)"\n'
        f"      priority: 100\n"
        f"      entryPoints:\n"
        f"        - web\n"
        f"      middlewares:\n"
        f"        - {force_https_mw}@file\n"
        f"      service: {slug}-auto-gate-svc\n"
        f"  services:\n"
        f"    {slug}-auto-gate-svc:\n"
        f"      loadBalancer:\n"
        f"        servers:\n"
        f'          - url: "http://{proxy}:{proxy_port}"\n'
    )


def resolve_access(labels, app_name=""):
    """Collapse mode + groups labels into (is_public, allowed_groups) under
    DEFAULT-DENY by delegating to the canonical resolve_auth_mode (the single
    source of truth in helpers/labels_schema). Returns the (is_public,
    allowed_groups) pair this script's provisioner needs rather than the
    admin's (mode, groups, is_public) display triple. Warnings raised by the
    canonical are forwarded to stderr; never fails the sync."""
    _mode, allowed, is_public = resolve_auth_mode(labels, app_name)
    for w in last_warnings():
        print(f"dashboard-sync/warn {w}", file=sys.stderr)
    return (True, []) if is_public else (False, allowed)
