#!/usr/bin/env python3
"""Fail on a sentence written in two places.

Every tracked text file is reduced to its prose, then split into sentences:
comment markers and string quotes stripped, wrapped lines joined. Prose files
(Markdown, text) are prose throughout. In code, prose is comments, Python
triple-quoted strings, shell heredocs and echo strings, and YAML block scalars
and quoted values; the code around them is jscpd's to compare. A README
generated from module headers repeats those headers by design and is skipped.
A sentence of eight or more words that is mostly words, and appears twice
anywhere, is a duplicate: an explanation belongs in one place, which the
other places point to.

.github/duplicate-sentences-debt.txt lists the duplicates the tree carries
today. A duplicate not on it fails; so does an entry that is no longer
duplicated, so the list only shrinks.

    python3 .github/scripts/duplicate_sentences.py           check
    python3 .github/scripts/duplicate_sentences.py --list    print every duplicate
"""
from __future__ import annotations

import re
import subprocess
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
DEBT = ROOT / ".github" / "duplicate-sentences-debt.txt"
MIN_WORDS = 8
SKIP_SUFFIXES = (".lock", ".png", ".jpg", ".svg", ".ico", ".gz")
SKIP_FILES = {DEBT.relative_to(ROOT).as_posix()}

_MARKER = re.compile(r"^\s*(?:\{#|#+|//+|--|\*|;+|>)?\s?")
_QUOTES = re.compile(r"^\s*[fbr]?[\"']{1,3}|[\"']{1,3}\s*\)?,?\s*$")
_SPLIT = re.compile(r"(?<=[.!?:;])\s+(?=[A-Z`\"'(<\[])|\s+--\s+")
_WORD = re.compile(r"[A-Za-z][A-Za-z'-]*")
_MD_COMMENT = re.compile(r"<!--.*?-->", re.S)
GENERATED = "<!-- Generated by"

HASH_COMMENTED = (".toml", ".cfg", ".ini", ".conf", ".service", ".timer",
                  ".gitignore", ".dockerignore", ".env", ".example")
SLASH_COMMENTED = (".go", ".js", ".mjs", ".ts", ".css")

_HASH_COMMENT = re.compile(r"^\s*(?:#|\{#)")
_SLASH_COMMENT = re.compile(r"^\s*(?://|/\*|\*)")
_HEREDOC = re.compile(r"<<-?\s*['\"]?([A-Za-z_]\w*)['\"]?")
_ECHO = re.compile(r"^\s*echo\s+(?:-\w+\s+)*([\"'])(.*)\1")
_BLOCK_SCALAR = re.compile(r"^(\s*)(?:-\s+)?[^#\s][^#]*:\s*([>|])[-+]?\s*$")
_QUOTED_VALUE = re.compile(r"^\s*(?:-\s+)?[\w.-]+:\s*([\"'])(.+)\1\s*$")
_TRIPLE = re.compile(r"\"\"\"|'''")
# Ends the paragraph on its line: a YAML value is one string, not part of the
# next key's.
_END = "\x1e"


def _kind(rel: str, text: str) -> str:
    name = rel.rsplit("/", 1)[-1]
    base = name[:-3] if name.endswith(".j2") else name
    first = text.split("\n", 1)[0]
    if base.endswith(".py") or (first.startswith("#!") and "python" in first):
        return "python"
    if base.endswith((".sh", ".bash")) or (first.startswith("#!") and "sh" in first):
        return "shell"
    if base.endswith((".yml", ".yaml")):
        return "yaml"
    if base.endswith(SLASH_COMMENTED):
        return "slash"
    if base.endswith(HASH_COMMENTED) or base in ("Dockerfile", "Makefile"):
        return "hash"
    return "prose"


def _python(lines: list[str]) -> list[str]:
    out, inside = [], False
    for line in lines:
        marks = len(_TRIPLE.findall(line))
        if inside or marks:
            if not inside and marks:
                line = _TRIPLE.split(line, 1)[1]
            out.append(_TRIPLE.sub("", line))
            inside = inside != (marks % 2 == 1)
        elif _HASH_COMMENT.match(line):
            out.append(line)
        else:
            out.append("")
    return out


def _shell(lines: list[str]) -> list[str]:
    out, tag = [], None
    for line in lines:
        if tag is not None:
            if line.strip() == tag:
                tag = None
                out.append("")
            else:
                out.append(line)
            continue
        heredoc = _HEREDOC.search(line)
        echo = _ECHO.match(line)
        if heredoc and not _HASH_COMMENT.match(line):
            tag = heredoc.group(1)
            out.append("")
        elif echo:
            out.append(echo.group(2))
        elif _HASH_COMMENT.match(line):
            out.append(line)
        else:
            out.append("")
    return out


def _yaml(lines: list[str]) -> list[str]:
    """Comments, folded (>) block scalars and quoted values. A literal (|)
    block is code: a shell script or a file's content."""
    out, indent, keep = [], None, False
    for line in lines:
        depth = len(line) - len(line.lstrip())
        if indent is not None and (not line.strip() or depth > indent):
            out.append(line if keep else "")
            continue
        indent = None
        block = _BLOCK_SCALAR.match(line)
        quoted = _QUOTED_VALUE.match(line)
        if _HASH_COMMENT.match(line):
            out.append(line)
        elif block:
            indent, keep = len(block.group(1)), block.group(2) == ">"
            out.append("")
        elif quoted:
            out.append(quoted.group(2) + _END)
        else:
            out.append("")
    return out


def prose(rel: str, text: str) -> str:
    """`text` with every line that is not prose blanked, line numbers kept."""
    kind = _kind(rel, text)
    if kind == "prose":
        return text
    lines = text.split("\n")
    if kind == "python":
        kept = _python(lines)
    elif kind == "shell":
        kept = _shell(lines)
    elif kind == "yaml":
        kept = _yaml(lines)
    else:
        pattern = _SLASH_COMMENT if kind == "slash" else _HASH_COMMENT
        kept = [line if pattern.match(line) else "" for line in lines]
    return "\n".join(kept)


def normalize(sentence: str) -> str:
    return " ".join(re.sub(r"[^a-z0-9 ]+", " ", sentence.lower()).split())


def sentences(text: str):
    """(line, sentence) for each prose sentence in `text`."""
    paragraph: list[str] = []
    start = 0

    def flush():
        for sentence in _SPLIT.split(" ".join(paragraph)):
            sentence = sentence.strip()
            tokens = sentence.split()
            words = [t for t in tokens if _WORD.fullmatch(t.strip(".,;:()`\"'"))]
            if len(_WORD.findall(sentence)) >= MIN_WORDS and len(words) >= 0.7 * len(tokens):
                yield start, sentence

    for number, raw in enumerate(text.splitlines(), 1):
        ends = raw.endswith(_END)
        line = _QUOTES.sub("", _MARKER.sub("", raw.rstrip(_END).rstrip()).strip())
        if line:
            if not paragraph:
                start = number
            paragraph.append(line)
        if ends or not line:
            yield from flush()
            paragraph = []
    yield from flush()


def duplicates() -> dict[str, list[str]]:
    """Normalized sentence -> the places it appears, for every duplicate."""
    files = subprocess.run(["git", "-C", str(ROOT), "ls-files"], check=True,
                           capture_output=True, text=True).stdout.splitlines()
    places: dict[str, list[str]] = defaultdict(list)
    first: dict[str, str] = {}
    for rel in files:
        path = ROOT / rel
        if rel in SKIP_FILES or rel.endswith(SKIP_SUFFIXES) or not path.is_file():
            continue
        try:
            text = path.read_text(encoding="utf-8")
        except (UnicodeDecodeError, OSError):
            continue
        if text.startswith(GENERATED):
            continue
        if rel.endswith(".md"):
            text = _MD_COMMENT.sub(lambda m: "\n" * m.group(0).count("\n"), text)
        for line, sentence in sentences(prose(rel, text)):
            key = normalize(sentence)
            places[key].append(f"{rel}:{line}")
            first.setdefault(key, sentence)
    return {first[k]: v for k, v in places.items() if len(v) > 1}


def debt() -> set[str]:
    return {normalize(line) for line in DEBT.read_text(encoding="utf-8").splitlines()
            if line.strip() and not line.startswith("#")}


def main(argv: list[str]) -> int:
    found = duplicates()
    if "--list" in argv:
        for sentence in sorted(found):
            print(sentence)
        return 0
    known = debt()
    new = {s: p for s, p in found.items() if normalize(s) not in known}
    stale = known - {normalize(s) for s in found}
    for sentence, places in sorted(new.items()):
        print(f"duplicate sentence: {sentence}\n  " + "\n  ".join(places))
    for entry in sorted(stale):
        print(f"no longer duplicated, delete it from {DEBT.name}: {entry}")
    if new or stale:
        print(f"\n{len(new)} new duplicate(s), {len(stale)} stale debt entry(ies). "
              "Keep the explanation in one place and point to it from the others.")
        return 1
    print(f"no new duplicate sentences ({len(known)} carried in {DEBT.name})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
