#!/usr/bin/env python3
"""Merge a key/value into <inventory_dir>/.bootstrap-output.yml.

Bootstrap-time invocations (bootstrap.yml's IP rewrite, fresh_install.yml's
Dokploy-admin API key mint) used to write directly into the inventory
clone (hosts.yml, vault.sops.yml). Under a permanent Semaphore worker
the clone is task-scoped and these mutations vanish on the next git
pull, so the workflow is now: emit values into a gitignored
.bootstrap-output.yml; the operator (or the bench, acting as operator)
copies them into catenahq/inventories via a normal PR.

File shape:

    # header comment (regenerated on every write)
    ---
    inventory_dir: <path>
    hosts:
      <hostname>:
        ansible_host: <ip>
    vault:
      vault_dokploy_api_key: <key>

This helper merges a single (section, host, key, value) tuple into the
file atomically (temp-file + os.replace). Stdlib + PyYAML only -- no
ruamel dep; comment preservation is not load-bearing because the
header is regenerated.

Usage:
    helpers/bootstrap_output.py \\
        --inventory-dir <inv> \\
        --section {hosts|vault} \\
        [--host <name>]              # required for --section hosts
        --key <key> --value <value>

    # Example: tailnet IP for a host entry
    helpers/bootstrap_output.py \\
        --inventory-dir inventory/test \\
        --section hosts --host testvm-a \\
        --key ansible_host --value 100.123.45.67

    # Example: Dokploy API key
    helpers/bootstrap_output.py \\
        --inventory-dir inventory/test \\
        --section vault \\
        --key vault_dokploy_api_key --value abcdef...

Exit codes:
    0 -- merge succeeded (no-op or update).
    2 -- bad arguments / IO error.
"""
from __future__ import annotations

import argparse
import os
import sys
import tempfile
from pathlib import Path

import yaml

HEADER = """\
# GENERATED by helpers/bootstrap_output.py (called from playbooks/
# bootstrap.yml + fresh_install.yml). Gitignored; never commit. Operator
# copies the values below into catenahq/inventories ahead of subsequent
# invocations.
#
# Apply steps:
#   1. Set hosts[<host>].ansible_host in <inventory>/hosts.yml under the
#      `vps:` group (or use helpers/update_inventory_host.py).
#   2. Merge `vault:` entries via `sops --set` on
#      <inventory>/group_vars/all/vault.sops.yml.
#   3. Commit + push catenahq/inventories; bump the submodule in ops/.
"""


def _load(path: Path) -> dict:
    if not path.is_file():
        return {}
    try:
        data = yaml.safe_load(path.read_text()) or {}
    except yaml.YAMLError as exc:
        print(f"error: {path} is not valid YAML: {exc}", file=sys.stderr)
        sys.exit(2)
    return data if isinstance(data, dict) else {}


def _atomic_write(path: Path, body: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp = tempfile.mkstemp(
        prefix=".bootstrap-output.", suffix=".tmp", dir=str(path.parent)
    )
    try:
        with os.fdopen(fd, "w") as f:
            f.write(body)
        # chmod is best-effort: FUSE-mounted filesystems (e.g. the
        # veracrypt NTFS volume the operator's bench runs from)
        # synthesise modes via fmask/dmask and raise EPERM on chmod.
        # The mode bits in the YAML still constrain who can read the
        # file via the mount-level mask; failing the bootstrap solely
        # over a chmod no-op is the wrong trade.
        try:
            os.chmod(tmp, 0o600)
        except PermissionError:
            pass
        os.replace(tmp, path)
    except Exception:
        try:
            os.unlink(tmp)
        except OSError:
            pass
        raise


def apply_to_inventory(inv_dir: Path) -> list[str]:
    """Apply hosts.<name>.ansible_host from .bootstrap-output.yml into
    <inv_dir>/hosts.yml (the `vps:` group).

    bootstrap.yml joins the tailnet and rewrites the host's ansible_host in
    its IN-MEMORY inventory (add_host) + emits .bootstrap-output.yml, but a
    SEPARATE site.yml / validate.yml invocation (as `catena install` runs
    each stage) reads hosts.yml, where the entry is still the 0.0.0.0
    placeholder. Applying the emitted IP here makes the later stages target
    the real tailnet address. Returns the list of applied
    "<host>.ansible_host=<ip>" (empty == nothing to apply)."""
    out_path = inv_dir / ".bootstrap-output.yml"
    hosts = (_load(out_path).get("hosts") or {})
    if not hosts:
        return []
    hosts_yml = inv_dir / "hosts.yml"
    inv = _load(hosts_yml)
    vps = (
        inv.setdefault("all", {}).setdefault("children", {})
        .setdefault("vps", {}).setdefault("hosts", {})
    )
    applied: list[str] = []
    for host, entry in hosts.items():
        ip = (entry or {}).get("ansible_host")
        if not ip:
            continue
        vps.setdefault(host, {})["ansible_host"] = ip
        applied.append(f"{host}.ansible_host={ip}")
    if applied:
        _atomic_write(
            hosts_yml,
            yaml.safe_dump(inv, default_flow_style=False, sort_keys=False),
        )
    return applied


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(prog="bootstrap_output.py")
    ap.add_argument("--inventory-dir", required=True, type=Path)
    ap.add_argument("--section", required=True, choices=("hosts", "vault"))
    ap.add_argument("--host", help="Required when --section=hosts")
    ap.add_argument("--key", required=True)
    ap.add_argument("--value", required=True)
    args = ap.parse_args(argv[1:])

    if args.section == "hosts" and not args.host:
        print("error: --host is required when --section=hosts", file=sys.stderr)
        return 2

    inv_dir: Path = args.inventory_dir
    out_path = inv_dir / ".bootstrap-output.yml"
    data = _load(out_path)
    data.setdefault("inventory_dir", str(inv_dir))
    data.setdefault("hosts", {})
    data.setdefault("vault", {})

    if args.section == "hosts":
        host_entry = data["hosts"].setdefault(args.host, {})
        host_entry[args.key] = args.value
    else:
        data["vault"][args.key] = args.value

    body = HEADER + yaml.safe_dump(
        data, default_flow_style=False, sort_keys=True, indent=2
    )
    _atomic_write(out_path, body)
    print(f"{out_path}: merged {args.section}.{args.host + '.' if args.host else ''}{args.key}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
