#!/usr/bin/env python3
"""Merge a key/value into <inventory_dir>/.bootstrap-output.yml.

bootstrap.yml rewrites the host's ansible_host in its IN-MEMORY inventory
once the VPS joins the tailnet, but a later `catena install` stage reads
hosts.yml off disk, where the entry is still the placeholder. So the value
is emitted here, into a gitignored file the operator copies into their
inventory (and apply_to_inventory() applies for the in-flight run).

NO SECRET goes through this file. Every Catena secret, including the
Portainer API key, lives in the on-box store at /etc/catena/config.json
(0b), written there directly by reconcile/roles/portainer.

File shape:

    # header comment (regenerated on every write)
    ---
    inventory_dir: <path>
    hosts:
      <hostname>:
        ansible_host: <ip>

This helper merges a single (host, key, value) tuple into the file
atomically (temp-file + os.replace). Stdlib + PyYAML only -- no ruamel dep;
comment preservation is not load-bearing because the header is regenerated.

Usage:
    helpers/bootstrap_output.py \\
        --inventory-dir inventory/test \\
        --host testvm-a \\
        --key ansible_host --value 100.123.45.67

Exit codes:
    0 -- merge succeeded (no-op or update).
    2 -- bad arguments / IO error.
"""
from __future__ import annotations

import argparse
import os
import sys
import tempfile
from pathlib import Path

import yaml

HEADER = """\
# GENERATED by helpers/bootstrap_output.py (called from playbooks/
# bootstrap.yml). Gitignored; never commit. Non-secret only.
#
# To apply by hand: set hosts[<host>].ansible_host in <inventory>/hosts.yml
# under the `vps:` group. `catena install` does this for you between stages.
"""


def _load(path: Path) -> dict:
    if not path.is_file():
        return {}
    try:
        data = yaml.safe_load(path.read_text()) or {}
    except yaml.YAMLError as exc:
        print(f"error: {path} is not valid YAML: {exc}", file=sys.stderr)
        sys.exit(2)
    return data if isinstance(data, dict) else {}


def _atomic_write(path: Path, body: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp = tempfile.mkstemp(
        prefix=".bootstrap-output.", suffix=".tmp", dir=str(path.parent)
    )
    try:
        with os.fdopen(fd, "w") as f:
            f.write(body)
        # chmod is best-effort: FUSE-mounted filesystems (e.g. the
        # veracrypt NTFS volume the operator's bench runs from)
        # synthesise modes via fmask/dmask and raise EPERM on chmod.
        # The mode bits in the YAML still constrain who can read the
        # file via the mount-level mask; failing the bootstrap solely
        # over a chmod no-op is the wrong trade.
        try:
            os.chmod(tmp, 0o600)
        except PermissionError:
            pass
        os.replace(tmp, path)
    except Exception:
        try:
            os.unlink(tmp)
        except OSError:
            pass
        raise


def apply_to_inventory(inv_dir: Path) -> list[str]:
    """Apply hosts.<name>.ansible_host from .bootstrap-output.yml into
    <inv_dir>/hosts.yml (the `vps:` group).

    bootstrap.yml joins the tailnet and rewrites the host's ansible_host in
    its IN-MEMORY inventory (add_host) + emits .bootstrap-output.yml, but a
    SEPARATE site.yml / validate.yml invocation (as `catena install` runs
    each stage) reads hosts.yml, where the entry is still the 0.0.0.0
    placeholder. Applying the emitted IP here makes the later stages target
    the real tailnet address. Returns the list of applied
    "<host>.ansible_host=<ip>" (empty == nothing to apply)."""
    out_path = inv_dir / ".bootstrap-output.yml"
    hosts = (_load(out_path).get("hosts") or {})
    if not hosts:
        return []
    hosts_yml = inv_dir / "hosts.yml"
    inv = _load(hosts_yml)
    vps = (
        inv.setdefault("all", {}).setdefault("children", {})
        .setdefault("vps", {}).setdefault("hosts", {})
    )
    applied: list[str] = []
    for host, entry in hosts.items():
        ip = (entry or {}).get("ansible_host")
        if not ip:
            continue
        vps.setdefault(host, {})["ansible_host"] = ip
        applied.append(f"{host}.ansible_host={ip}")
    if applied:
        _atomic_write(
            hosts_yml,
            yaml.safe_dump(inv, default_flow_style=False, sort_keys=False),
        )
    return applied


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(prog="bootstrap_output.py")
    ap.add_argument("--inventory-dir", required=True, type=Path)
    ap.add_argument("--host", required=True)
    ap.add_argument("--key", required=True)
    ap.add_argument("--value", required=True)
    args = ap.parse_args(argv[1:])

    inv_dir: Path = args.inventory_dir
    out_path = inv_dir / ".bootstrap-output.yml"
    data = _load(out_path)
    data.setdefault("inventory_dir", str(inv_dir))
    data.setdefault("hosts", {})
    data["hosts"].setdefault(args.host, {})[args.key] = args.value

    body = HEADER + yaml.safe_dump(
        data, default_flow_style=False, sort_keys=True, indent=2
    )
    _atomic_write(out_path, body)
    print(f"{out_path}: merged hosts.{args.host}.{args.key}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
